name: First Interaction Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            🎉 Hi @${{ github.event.issue.user.login }}! Welcome to the repository! 🥳 Thanks for opening your first issue here. We appreciate your contribution! 🙌 If you have any questions, feel free to ask. 😊
          pr-message: >
            🚀 Hi @${{ github.event.pull_request.user.login }}! Welcome and thank you for submitting your first pull request. 🎉 We value your contribution. Please ensure that you have followed our contribution guidelines. 📜 If you have any questions, let us know. 😊
