name: Common Greeting

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Greet on new issue or pull request
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" \
              -d '{"body": "💡 Hi @${{ github.actor }}! Thanks for opening this issue. We appreciate your efforts and suggestions. Keep up the great work! 🚀"}'
          elif [ "${{ github.event_name }}" == "pull_request_target" ]; then
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
              -d '{"body": "✨ Hi @${{ github.actor }}! Thanks for opening this pull request. Your contributions are highly valued. Keep up the good work! 🙌"}'
          fi
