name: Subsequent Interaction

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Check if first interaction
        id: check
        run: |
          issues=$(gh api -X GET "repos/${{ github.repository }}/issues?state=all&creator=${{ github.actor }}" | jq length)
          prs=$(gh api -X GET "repos/${{ github.repository }}/pulls?state=all&creator=${{ github.actor }}" | jq length)
          if [ $((issues + prs)) -gt 1 ]; then
            echo "::set-output name=first::false"
          else
            echo "::set-output name=first::true"
          fi
      - name: Subsequent interaction message
        if: steps.check.outputs.first == 'false'
        run: |
          if [ ${{ github.event_name }} == 'issues' ]; then
            gh api -X POST "repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" -f body='💡 Hi @${{ github.actor }}! Thanks for your continued contributions! We appreciate your efforts and suggestions. Keep up the great work! 🚀'
          elif [ ${{ github.event_name }} == 'pull_request_target' ]; then
            gh api -X POST "repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" -f body='✨ Hi @${{ github.actor }}! Thanks for submitting another pull request. Your continuous improvements are highly valued. Keep contributing! 🙌'
          fi
